export const data = [
  {
    company: 'Allium Money (Brighten Home Loans)',
    bank: 'First Federal',
    direct_bank: 'ME Bank',
    assistance: 'RACQ (QLD Only)',
  },
  {
    company: 'Adelaide Bank',
    bank: 'Firstmac',
    direct_bank: 'Medfin',
    assistance: 'Redzed',
  },
  {
    company: 'AMFIN',
    bank: 'Funding',
    direct_bank: 'Money Place',
    assistance: 'Resimac',
  },
  {
    company: 'AMP Bank',
    bank: 'Gateway Bank',
    direct_bank: 'Mortgage Ezy',
    assistance: 'Salt and Lime',
  },
  {
    company: 'ANZ',
    bank: 'Granite Home Loans',
    direct_bank: 'Mortgage Mart',
    assistance: 'Shift',
  },
  {
    company: 'Australian Military Bank',
    bank: 'Great Southern Bank',
    direct_bank: 'Move Bank',
    assistance: 'St George/BOM/Bank SA',
  },
  {
    company: 'Auswide Bank',
    bank: 'Heartland',
    direct_bank: 'Seniors Finance',
    assistance: 'My State Suncorp',
  },
  {
    company: 'Bank Australia',
    bank: 'Hejaz Financial Services',
    direct_bank: 'NAB',
    assistance: 'Thinktank',
  },
  {
    company: 'Bank of China',
    bank: 'Heritage Bank',
    direct_bank: 'Now Finance',
    assistance: 'TMB/Firefighters/Uni Bank',
  },
  {
    company: 'Bank of Sydney',
    bank: 'Home Affordability Solutions',
    direct_bank: 'Oak Capital',
    assistance: 'UBank',
  },
  {
    company: 'BankVic (VIC Only coming soon)',
    bank: 'IMB (VIC Only)',
    direct_bank: 'ORDE Financial',
    assistance: 'Valiant Finance',
  },
  {
    company: 'Bankwest',
    bank: 'ING',
    direct_bank: 'P&N Bank (WA Only)',
    assistance: 'Victorian Mortgage Group',
  },
  {
    company: 'Better Mortgage Management',
    bank: 'Judo',
    direct_bank: 'Paramount Mortgages',
    assistance: 'Virgin Money',
  },
  {
    company: 'Beyond Bank Australia',
    bank: 'Keystart (WA Only)',
    direct_bank: 'Pepper',
    assistance: 'Westpac',
  },
  {
    company: 'Bluebay Home Loans',
    bank: 'La Trobe Financial',
    direct_bank: 'Pepper Asset',
    assistance: 'WISR',
  },
  {
    company: 'Bluestone Mortgages',
    bank: 'Latitude',
    direct_bank: 'Plenti (formerly RateSetter)',
    assistance: 'WLTH',
  },
  {
    company: 'BOQ',
    bank: 'Liberty Financial',
    direct_bank: 'Prime Capital',
    assistance: 'Zip Business',
  },
  {
    company: 'CBA',
    bank: 'MA Money',
    direct_bank: 'Prospa',
    assistance: '360MMS',
  },
  {
    company: 'Community First Bank',
    bank: 'Macquarie Bank & Leasing',
    direct_bank: 'Qudos Bank',
    assistance: '',
  },
];
